added namespace for AGP8 compatibility
Baseflow/flutter-google-api-availability pull request #43
Opened 2023-05-08 16:00 UTC by deckerst

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
adding namespace in `build.gradle` for compatibility with AGP 8

### :arrow_heading_down: What is the current behavior?
no behaviour change

### :new: What is the new behavior (if this is a feature change)?
no behaviour change

### :boom: Does this PR introduce a breaking change?
no

### :bug: Recommendations for testing
use AGP 8

### :memo: Links to relevant issues/docs
cf Flutter packages comment/solution:
- https://github.com/flutter/packages/commit/6284c2d4e46a5d289e77cb03a9457543b97f750b
- https://github.com/flutter/packages/commit/a86beafa8912609275225847198c9c0164957d09

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/BaseflowIT/flutter-google-api-availability/blob/main/CONTRIBUTING.md))
- [X] Relevant documentation was updated
- [X] Rebased onto current develop

2023-05-13 12:50 UTC, deckerst commented
@JeroenWeener could you please take a look at this PR?

2023-05-15 10:02 UTC, JeroenWeener requested changes
Thank you for your contribution!

Could you add the `namespace` property to the `example` gradle file as well (without the if-statement)?

Before we merge, could you update the `CHANGELOG` and `pubspec.yaml`?

2023-05-23 10:06 UTC, TheHypnoo commented
@deckerst Hi, could you move forward with this PR? Thank you

2023-05-24 07:59 UTC, mvanbeusekom approved these changes
LGTM, modules a small nit would be great if you'd be able to send a small update for that.

2023-05-24 07:59 UTC, mvanbeusekom commented on google_api_availability_android/CHANGELOG.md
> +* Add support of namespace property to support Android Gradle Plugin (AGP) 8
nit: entries in the changelog should use present tense indicative for verbs, with "this version" as an implied subject. For example, "Adds cool new feature.", not "Add" or "Added".
```suggestion
* Adds support for the namespace property to support Android Gradle Plugin (AGP) 8.
```

2023-05-26 08:48 UTC, TheHypnoo commented
Could this be mergeable? Thank you! @JeroenWeener @mvanbeusekom

2023-05-26 08:55 UTC, merged